<h1>Gift Factory Made your Order</h1>
<form id="blogPost" method="post" action="<?php echo $this->getUrl("gifts/post/submit")?>">
    <div class="form-group">
        <label for="title">Name:</label>
        <input type="text" class="input" name="title" id="title" required>
        <label for="email">Email:</label>
        <input type="text" class="input" name="email" id="email" required>
        <label for="contact">Contact:</label>
        <input type="number" class="input" name="contact" id="contact">
        <label for="company">Organization:</label>
        <input type="text" class="input" name="company" id="company">
        <textarea name="content" rows="10" cols="30">Message/Requirement</textarea>

        <button id="blogSubmit" type="submit" class="btn btn-default">Submit</button>
    </div>
</form>