<h1>Gift Factory Made your Order</h1>
<form id="blogPost" method="post" action="<?php echo $this->getUrl("gifts/post/submit")?>" enctype="multipart/form-data">
    <div class="form-group">
        <label for="title">Name:</label>
        <input type="text" class="input" name="title" id="title" required>
        <label for="email">Email:</label>
        <input type="text" class="input" name="email" id="email" required>
        <label for="contact">Contact:</label>
        <input type="tel" class="input" name="contact" id="contact">
        <label for="company">Organization:</label>
        <input type="text" class="input" name="company" id="company">
        <textarea name="message" rows="10" cols="30">Message/Requirement</textarea>
        <label for="files"><span>Upload Files</span></label>
        <input type="file" name="files" id="files" accept="image/*, application/pdf" multiple />

        <button id="blogSubmit" type="submit" class="btn btn-default">Submit</button>
    </div>
</form>